# Generated by Django 4.2.1 on 2023-06-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_goodincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_addres', models.TextField(verbose_name='Delivery address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
