# Generated by Django 4.2.1 on 2023-05-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Publisher name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Publisher description')),
            ],
        ),
    ]
