# Generated by Django 4.2.1 on 2023-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0004_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Book name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book description')),
            ],
        ),
    ]
