# Generated by Django 4.2.1 on 2023-06-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0007_rename_autors_autor_rename_books_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.autor', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
