# Generated by Django 4.2.1 on 2023-06-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0008_book_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.serie', verbose_name='Autor'),
        ),
    ]
