# Generated by Django 4.2.1 on 2023-06-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0009_autor_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.publisher', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.serie', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Genre Publisher'),
        ),
    ]
