# Generated by Django 4.2.1 on 2023-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0011_remove_autor_serie_remove_genre_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='-', upload_to='uploads/%Y/%m/%d/', verbose_name='Book picture'),
            preserve_default=False,
        ),
    ]
