# Generated by Django 4.2.1 on 2023-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0013_remove_book_description_book_age_book_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='updated'),
        ),
    ]
