# Generated by Django 4.2.1 on 2023-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0014_alter_book_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, default=1999, null=True, verbose_name='Year'),
        ),
    ]
